name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Test on Node

    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - run: pushd example && yarn && popd 
      - run: yarn lint
      - run: yarn build
